services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_HOST=0.0.0.0

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  evidently:
    image: evidently/service
    ports:
      - "8085:8085"
